### ISSUE TITLE
Remove yandex/appmetrica from necessary deps

### ISSUE THREAD

**Issue by LionisIAm** [cleveradssolutions/CAS-Android#1]
According to yandex metrica requires separate process - it causes crashes while initializing (with 100% crash rate). 
Read more here https://github.com/yandexmobile/yandex-ads-sdk-android/issues/41
We are not adding yandex as dep of our app, but "com.cleversolutions.ads" library does. 
We do not want to use yandex as mediation ad-provider.
Please provide a way to use CAS without yandex in deps at all.

**Comment by Str4tos** [comment]
Hi @LionisIAm 

CleverAdsSolutions don't have a strong dependency on any mediation SDK. You can choose the networks you like and not implemented others.  

To achieve the desired result, you can implemented CAS SDK without mediation dependencies:
```Gradle
dependencies {
    implementation 'com.cleversolutions.ads:cas-sdk:1.4.+' 
}
```
After that, you need to implemented the any mediation SDKs by [following Step 3](https://github.com/cleveradssolutions/CAS-Android#step-3-add-mediation-sdk), except com.yandex.android.  

Another way would be to exclude com.yandex.android dependency using gradle:
```gradle
dependencies {
    implementation('com.cleversolutions.ads:cas-sdk-teen:1.4.+') {
        exclude group: 'com.yandex.android'
    }
}
```

Thanks!

**Comment by LionisIAm** [comment]
Thanks! 
It works
