### ISSUE TITLE
GradleException: CAS Gradle Plugin: no build variants found for the module rtn-cas-ads. The plugin requires at least one build variant that uses in Application build.

### ISSUE THREAD

**Issue by asdfv** [cleveradssolutions/CAS-Android#12]
I am adding CAS Android SDK to React Native Fabric module.
Following the manual I added `repositories` in `settings.gradle` and applied plugin to `build.gradle` in fabric module, then setting up `cas` plugin.

`mobile-app/android/settings.gradle`
```groovy
dependencyResolutionManagement {
  repositories {
    google()
    mavenCentral()
    maven {
      name = "IronSourceAdsRepo"
      url = "https://android-sdk.is.com/"
      content { it.includeGroup("com.ironsource.sdk") }
    }
...
```

`mobile-app/modules/RTNCasAds/android/build.gradle`
```groovy
plugins {
    id("com.cleveradssolutions.gradle-plugin") version "3.9.7.1"
}

cas {
    casId = "testId"
    useAdvertisingId = true
    includeOptimalAds = true
}
```

When I am trying to run or sync I have an error:
> Caused by: org.gradle.api.GradleException: CAS Gradle Plugin: no build variants found for the module rtn-cas-ads. The plugin requires at least one build variant that uses in Application build.
	at com.cleveradssolutions.gradleplugin.CASPlugin.handleAfterEvaluate(CASPlugin.kt:58)

Build variants `debug` and `release` are presented in `mobile-app/modules/RTNCasAds/android/build.gradle`.

There are full versions of settings and build gradle in my Fabric module:
[build.gradle.txt](https://github.com/user-attachments/files/18210438/build.gradle.txt)
[settings.gradle.txt](https://github.com/user-attachments/files/18210440/settings.gradle.txt)

![image](https://github.com/user-attachments/assets/5634b135-67a7-4704-95a0-0b4d5f6b091e)

**Comment by Str4tos** [comment]
Hi @asdfv, thank you for creating the issue.
To resolve this error, please move the declaration of our plugin after the declaration of if('com.android.library') or id('com.android.application'). 

```gradle
plugins {
    id("com.android.library")
    id("kotlin-android")
    ...
    id("com.cleveradssolutions.gradle-plugin") version "3.9.7.1"
}
```

The order of plugin declarations is important for proper functionality, and this should fix the issue you're experiencing.
Thank you.

**Comment by asdfv** [comment]
Hi @Str4tos, thank you for quick response.
Indeed reordering of plugins was the key to solve this GradleException. So this specific Exception is solved. BTW it would be good to add this detail to the manual [here](https://github.com/cleveradssolutions/CAS-Android/wiki#option-1-plugin-integration).

So this issue can be closed, but just in case you can help me again with gradle:

For reordering I changed `apply plugin` construction for 'com.android.library', 'com.facebook.react', 'org.jetbrains.kotlin.android' to `plugins {}` block as in your example, next I had an issue with resolving dependencies for Cas SDK so I moved `repository` section that declaring repos for these dependencies from `settings.gradle` to `allprojects.repositories` section in the root `build.gradle` file (it is on same level with `settings.gradle`) that was there as a part of default ReactNative configuration. After that the gradle sync was successful.

But when I run the project I have a next issue: ` Cannot change dependencies of dependency configuration ':rtn-cas-ads:implementation' after it has been included in dependency resolution.`. I even removed `dependencies.implementation` block from rtn-cas-ads-`build.gradle` with no luck. 

My rtn-cas-ads-`build.gradle`:  [build.gradle.txt](https://github.com/user-attachments/files/18211767/build.gradle.txt)

**Comment by Str4tos** [comment]
> Cannot change dependencies of dependency configuration ':rtn-cas-ads:implementation' after it has been included in dependency resolution

Unfortunately, we need to investigate this issue and may need to update our Gradle plugin. While we are working on a solution, you can temporarily integrate the CAS SDK without the Gradle plugin by declaring simple dependencies.

Please create a new issue with a detailed description of the problem, and we will try to provide you with a solution as soon as possible. If possible, please share a minimal project example to help us reproduce the issue.

Thank you.

**Comment by Str4tos** [comment]
Hello @asdfv

We are continuing to investigate the issue with updating dependencies in our Gradle plugin.

Try add the CAS SDK dependency to your advertising module to use it in your code:
```
dependencies {
   implementation("com.cleveradssolutions:cas-sdk:3.9.8")
}
```

And add the CAS Gradle Plugin to your main application module to enable automatic configuration and include the required adapters.

Make sure that the versions of the SDK dependency and the Gradle plugin match.

We have tested this, and when the Gradle plugin is added to the main application module, the issue described above does not occur.
