### ISSUE TITLE
Banner loading stuck on "BannerView(320, 50): Already loading"

### ISSUE THREAD

**Issue by asdfv** [cleveradssolutions/CAS-Android#13]
I am adding CAS-Android SDK to react native app. I setup dependencies (without plugin - there were some issues), build `MediationManager` and enabled test mode. For react native I am using new architecture and Fabric native view.
I added `CASBannerView` programmatically to my wrapper `RTNCasBanner : LinearLayout` which is `LinearLayout` compound view. Also tried adding `CASBannerView` in xml layout with same result.
When app is started there is no Banner, in logs I can see this:

<details> 
  <summary>Logs</summary>

09:26:20.358  E  [Integration] MISSING ADAPTERS: Banner, Interstitial, Native, Rewarded 
09:26:20.359  E  [Integration] MISSING ADAPTERS: Banner, Interstitial, Rewarded
09:26:20.359  E  [Integration] MISSING ADAPTERS: Banner, Interstitial, Rewarded 
09:26:28.045  I  Ad manager initialization started
09:26:28.070  V  BannerView(320, 50): Try load ad after Size changed
09:26:28.070  V  BannerView(320, 50): Load next ad
09:26:28.131  V  BannerView(320, 50): Try load ad after container view presented but Ad not ready
09:26:28.131  V  BannerView(320, 50): Already loading
09:26:28.131  V  BannerView(320, 50): Try load ad after container view presented but Ad not ready
09:26:28.131  V  BannerView(320, 50): Already loading
</details>

So it looks like the banner is not loaded and also MediationManager is not initialized (no log "Ad manager initialized"). Also no one from the `CASBannerView.AdViewListener` callback are triggered. Another views on this layout are loaded ok.

The same code (copy-paste) working fine on pure Android. Also tried to pass `reactContext.applicationContext` to build `MediationManager` with same result.

<details> 
  <summary>Building `MediationManager` in `SimpleViewManager`</summary>

```kotlin
 private val adManager: MediationManager by lazy {
        CAS.settings.debugMode = true
        Log.i(TAG, "Ad manager initialization started")
        CAS.buildManager()
            .withManagerId("Test-id")
            .withTestAdMode(true)
            .withAdTypes(AdType.Banner)
            .withCompletionListener {
                if (it.error == null) {
                    Log.i(TAG, "Ad manager initialized")
                } else {
                    Log.e(TAG, "Ad manager initialization failed: " + it.error)
                }
            }
            .build(reactContext)
    }

    override fun createViewInstance(reactContext: ThemedReactContext): RTNCasBanner {
        return RTNCasBanner(reactContext, adManager).apply {
            layoutParams = ViewGroup.LayoutParams(
                LinearLayout.LayoutParams.MATCH_PARENT,
                LinearLayout.LayoutParams.WRAP_CONTENT,
            )
        }
    }
```
</details>

<details> 
  <summary>Adding banner to layout</summary>

```kotlin
        val bannerView = CASBannerView(context, manager)
        val label = findViewById<TextView>(R.id.label)
        label.text = "Here will be info about ads"
        bannerView.size = AdSize.BANNER
        bannerView.adListener = object : AdViewListener {
            override fun onAdViewLoaded(view: CASBannerView) {
                label.text = "Loaded"
                Log.d(TAG, "Banner Ad loaded and ready to present")
            }

            override fun onAdViewFailed(view: CASBannerView, error: AdError) {
                label.text = error.message
                println("Banner Ad received error: " + error.message)
            }

            override fun onAdViewPresented(view: CASBannerView, info: AdImpression) {
                label.text = "Presented: " + info.network
                Log.d(TAG, "Banner Ad presented from ${info.network}")
            }

            override fun onAdViewClicked(view: CASBannerView) {
                label.text = "Clicked"
                Log.d(TAG, "Banner Ad received Click action")
            }
        }
        addView(bannerView)
```
</details>

<details> 
  <summary>In React (size property is unused so far)</summary>

```js
const AdsViewWrapper: () => JSX.Element = () => {
    const {width, height} = Dimensions.get('window');
    return (
        <RTNCasBanner
            size="BANNER_SIZE"
            style={{ width: width, height: height }}
        />
    );
};
```
</details>

**Comment by Str4tos** [comment]
Hello, @asdfv Thank you for creating the issue.

Based on the logs you’ve shared, it seems that all entries are within the same second (09:26:28), and there are no other logs with the CAS.AI tag. The initialization of the CAS SDK and ad loading typically takes more time, so we kindly ask you to wait a bit longer and provide us with additional logs. You should see more detailed logs related to the initialization and loading process and can send them in a separate text file.

If for any reason you're unable to obtain more logs, please disable all filters and send us the full log file from your device, starting from the app launch.

Thank you!

**Comment by asdfv** [comment]
Hi @Str4tos, thanks you again for you feedback. I waited up to 10 minutes with no luck. Here is the log: 
[LogsNoBanner.txt](https://github.com/user-attachments/files/18231905/LogsNoBanner.txt)

**Comment by asdfv** [comment]
That is an interesting, if I put app in a background and back (in logs: 23:31:23.884  D  Activity Resumed) - adManager is initialized after that and ad is loaded. Only that it still not visible on the screen, but this looks more like RN layout issue. But why adManager initialization is started but not finished? 🤔
New logs: [Logs2.txt](https://github.com/user-attachments/files/18233190/Logs2.txt)

**Comment by Str4tos** [comment]
Hello @asdfv, thank you for providing the log file.

It might be more convenient for you to monitor the enabled log tags and filter with CAS.AI.

1. We can see that at 23:30:06, the CAS SDK was unable to detect your Activity to display the Google User Messaging Platform (UMP). This is evident from the message `Consent Flow: Activity is null`. In this case, the SDK initialization is paused and waits for the Activity. This may happen if `CAS.buildManager()` is called when an Activity has already been created but has not been passed to the CAS SDK. 

Please pass the Activity as a parameter to `.build(reactContext)`, where `reactContext` is the Activity.

2. At 23:31:23, it seems that you may have minimized and restored the app, which triggered the `Activity Resumed` event, allowing the CAS SDK to obtain the UI context and continue showing the Google UMP. However, the following error occurred:
```
The UMP SDK requires a valid application ID in your AndroidManifest.xml through a com.google.android.gms.ads.APPLICATION_ID meta-data tag.
```
To use Google UMP, you need to define the Google Application ID. While testing the integration, you can use the test ID. 
Add the following meta-data tag to your application's manifest:
```
<manifest>
  <application>
    ...
    <meta-data
        android:name="com.google.android.gms.ads.APPLICATION_ID"
        android:value="ca-app-pub-3940256099942544~3347511713"/>
  </application>
</manifest>
```
Please note that the ID above is a test ID, and your app will need to obtain its own ID for production, please follow the [Additional Google AdMob steps](https://github.com/cleveradssolutions/CAS-Android/wiki/Additional-Google-AdMob-steps) page.  

3. At 23:31:24, we see the log message `Ad manager initialized`, indicating the initialization was completed.

4. At 23:31:24, the CAS SDK loaded a test banner and displayed it on the screen.  
Did you see the banner on the screen? There may be an issue with the visibility of the View in your UI hierarchy.

**Comment by asdfv** [comment]
Thank you for detailed answer. Switching `reactContext` -> `activityContext` fixed the issue. Also setting `CasBannerView` in xml with predefined size `ads:bannerSize="Standard320x50"` helped with RN layout issue. Working with different sizes I will check later.
Also added test ID in manifest as you suggested, but not sure is required. I saw the confirmation bottomsheet about the Ads which appeared before app first start, is that required to show it or can be avoided?

**Comment by Str4tos** [comment]
You have seen the bottom sheet created by CAS for GDPR compliance; however, this is not the certified CPM for Google Ads. The CAS SDK can operate automatically with Google UMP to ensure compatibility with all current industry regulations. It is critically to review the [Google consent management requirements for serving ads in the EEA, the UK, and Switzerland (for publishers)](https://support.google.com/admanager/answer/13554116).

I would also like to mention that we have found a solution to your issue in our Gradle plugin and are ready to release the fix in the next few days.

**Comment by asdfv** [comment]
Thank you for explanation and looking forward for plugin fix - I am using regular dependencies so far.
Also closing this issue ✅
