### ISSUE TITLE
AppOpen AdType (Enhancement)

### ISSUE THREAD

**Issue by EgorSigolaev** [cleveradssolutions/CAS-Android#2]
Unfortunately, there are only 4 ad types available: Banner, Interstitial, Rewarded and None. Would be better to add AppOpen AdType instead of None for onAdRevenuePaid callback.

**Comment by Str4tos** [comment]
Thank you for creating the issue. We will address it in our upcoming SDK updates.

**Comment by Str4tos** [comment]
We have planned this enhancement for the CAS 3.6.0 update.  
Thank you for your patience

**Comment by Str4tos** [comment]
SDK v3.6.0 with new AdType has been released.
