### ISSUE TITLE
How to initialize CAS from outside of 

### ISSUE THREAD

**Issue by tabatinga0xffff** [cleveradssolutions/CAS-Android#3]
CAS is initialized by one of these functions:

```
       fun initialize(activity: Activity): MediationManager
       fun initialize(application: Application): MediationManager
       fun initialize(contextService: ContextService): MediationManager
```

What if I were to use this code, the one outside of `Activity` and `Application`, how would I initialize CAS?

```
FrameLayout mLayout;

//[................]


WindowManager wm = (WindowManager) getSystemService(WINDOW_SERVICE);
mLayout = new FrameLayout(this);
WindowManager.LayoutParams lp = new WindowManager.LayoutParams();
//[.............]
LayoutInflater inflater = LayoutInflater.from(this);
inflater.inflate(R.layout.action_bar, mLayout);
wm.addView(mLayout, lp);


//[................]

```

Namely, if I wanted to show adverts inside `mLayout`

**Comment by Str4tos** [comment]
Hello @tabatinga0xffff, 

Advertising initialization cannot occur simultaneously with View creation. Instead, you should call advertising initialization within the body of the `Application.onCreate()` function or for each `Activity.onCreate()`.  
Please save the reference to the created `MediationManager` in any convenient location for your usage.

After receiving the created ad manager, you can display ads anywhere in your application. If you want to show a Banner Ads, just create a `CASBannerView` and add it to your `FrameLayout` for display using the available Context.

To display fullscreen ads, you need to pass a reference to your Activity to the CAS SDK.

Please follow the instructions for displaying specific ad formats on our Wiki.

Thank you, and have a great day.

**Comment by tabatinga0xffff** [comment]
There's no way to display `Interstitial` on anything but an Activity? Not on `FrameLayout` as overlay? Or anything similar? @Str4tos

**Comment by Str4tos** [comment]
Hello @tabatinga0xffff,

Actually, in Android, when displaying Interstitial Ads, it's important to pass the current Activity as a parameter. This is because Interstitial Ads typically cover the entire screen and may require user interaction, such as dismissing the ad or clicking on it to proceed.  
You can take advantage of a variety of popular methods to obtain the current Activity for the context of your usage.

**Comment by tabatinga0xffff** [comment]
>Actually, in Android, when displaying Interstitial Ads, it's important to pass the current Activity as a parameter. 

Important for whom?

>You can take advantage of a variety of popular methods to obtain the current Activity for the context of your usage.

Yes, but I haven't asked "how to obtain the current Activity"

**Comment by EgorSigolaev** [comment]
CAS SDK is such a container of other different sdks (admob, meta, etc). Each of them requires Activity instance to show interstitial/rewarded ads. If you check out admob sdk, you will see that. Showing interstitial ads as Activity allows ad networks to obtain control over the ads (user interactions, clicks, dismisses). Ad Activity doesn't depend on your app lifecycle or other views. That's why Activity instance is required.

**Comment by tabatinga0xffff** [comment]
What can be done by `Banner + FrameLayout` and can't by  `Interstitial + Activity` is displaying it as an overlay over other apps. Or making it pop up as an overlay when a certain app on a phone receives focus or gets launched....  That's what I need.  No way, right?

**Comment by EgorSigolaev** [comment]
> What can be done by `Banner + FrameLayout` and can't by `Interstitial + Activity` is displaying it as an overlay over **other apps**. Or making it pop up as an overlay when a certain third-party app on a phone receives focus, gets launched, changes its state.... That's what I need. No way, right?

I assume you are trying to do something that is not acceptable by Google Play. Banner and Interstitial ads must be shown when you app has focus.

**Comment by tabatinga0xffff** [comment]
I assume that you shouldn't assume. Back to my question.

**Comment by tabatinga0xffff** [comment]
> You cannot display the Interstitial Ad Activity in the same way as a Banner Ad View without passing an instance of the application's Activity.

If I can't, will Chuck Norris be able to?

**Comment by Str4tos** [comment]
Chuck Norris doesn't need to worry about passing instances of Activities. He just stares at the screen, and ads pop up out of fear.
