### ISSUE TITLE
Not able to build after 3.9.6 upgrade 

### ISSUE THREAD

**Issue by balakumar-t** [cleveradssolutions/CAS-Android#9]
> Task :app:compressDebugAssets UP-TO-DATE
> Task :app:desugarDebugFileDependencies UP-TO-DATE
> Task :app:mergeDebugJniLibFolders UP-TO-DATE
> Task :app:mergeDebugNativeLibs UP-TO-DATE
> Task :app:stripDebugDebugSymbols UP-TO-DATE
> Task :app:validateSigningDebug UP-TO-DATE
> Task :app:writeDebugAppMetadata UP-TO-DATE
> Task :app:writeDebugSigningConfigVersions UP-TO-DATE
> Task :app:checkDebugDuplicateClasses FAILED

FAILURE: Build completed with 2 failures.

1: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':app:processDebugMainManifest'.
> Manifest merger failed with multiple errors, see logs

* Try:
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.

* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':app:processDebugMainManifest'.
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.lambda$executeIfValid$1(ExecuteActionsTaskExecuter

**Comment by Str4tos** [comment]
Hello, @balakumar-t 
Thank you for creating the issue. 

Just to confirm, is the problem you’re experiencing described in the lines below?
```
Error: 
 Attribute application@appComponentFactory value=(androidx.core.app.CoreComponentFactory) 
  from [androidx.core:core:1.13.0] AndroidManifest.xml:28:18-86 
 is also present at [com.android.support:support-compat:28.0.0] AndroidManifest.xml:22:18-91 
  value=(android.support.v4.app.CoreComponentFactory).
```

We are currently investigating the cause, but we haven’t been able to reproduce the issue yet. Could you please provide us with any relevant information that might help us replicate your environment? Specifically:
1. What dependencies does your project use aside from the CAS dependencies?
2. What version of Gradle is your project using?

We will keep you updated on the progress in resolving this issue.

Thank you!

**Comment by balakumar-t** [comment]
Attaching full log for reference
[396-Error.txt](https://github.com/user-attachments/files/17540281/396-Error.txt)

**Comment by balakumar-t** [comment]
The problem is Mintegral library, after disabling that I able to build the project with 3.9.6
![WhatsApp Image 2024-10-28 at 4 49 39 PM](https://github.com/user-attachments/assets/73238404-3d6d-4edb-aa5e-8c697da0c2dd)

**Comment by balakumar-t** [comment]
Can cas.ai release another version without Mintegral working version.

**Comment by balakumar-t** [comment]
Able to build with 3.9.6 after making the below changes.

android {
    ...
    configurations {
        all*.exclude group: 'com.android.support'
    }
}

dependencies {
    implementation 'androidx.core:core:1.13.0'
}

**Comment by Str4tos** [comment]
@balakumar-t Hello.
Sorry for the delay. We noticed that the latest version of the Mintegral SDK (version 16.8.71) still depends on the android.support library. We hope that Mintegral will update their library to use AndroidX in the next release.
As a workaround, you can add the following lines to the `gradle.properties` file of your Android project:
```gradle
android.enableJetifier=true  
android.useAndroidX=true
```

**Comment by balakumar-t** [comment]
@Str4tos - I was able to build after making the changes I mentioned above
